### PR TITLE
Add summary of previous question to each page

### PR DESCRIPTION
**Pull request by antw**
Summarises the previous question. By default shows the CO2 emissions of the two choices. If activated, also shows the reasons for each choice being correct or incorrect.

Screenshots are included below. I don't really the way it looks at all. I think it's completely unintuitive that the numbers shown have anything to do with the previous question. I tried [putting it above the progress bar]((https://cloud.githubusercontent.com/assets/4383/25664630/1f344504-3013-11e7-8949-f88b22bee6a3.png)) – which avoids the sense that it's just "floating" at the top of the page, and perhaps avoids the visitor from thinking that the numbers are connected to the *current* question – but it still doesn't feel right. Which do you prefer?

I know why this feature is needed, but it just feels... bolted on? An afterthought? I don't know what else we can do with it; there's nowhere natural in the UI to put this. Feedback would be much appreciated.

## Actions needed

* If you wish to merge without any changes, please check [this translation](https://github.com/quintel/etmobile/blob/077d83988dec5cf12f3f730a9ea776b5cee66302/src/data/locales/nl/summary.js#L5) before merging. In English it reads "Hide explanation". "Close explanation" would also be okay.

### First question

screen shot 2017-05-03 at 15 04 09

### Subsequent questions

screen shot 2017-05-03 at 15 04 14

* Correct and incorrect answers are coloured appropriately.
* The player's choice is highlighted with a blue border.

### Expanded (clicked / pressed)

screen shot 2017-05-03 at 15 04 20

* Full explanation texts shown with CO<sub>2</sub> emissions.
* Explanations may be closed by pressing the `?` again, or a "Hide explanations" button at the bottom.

### CODE REVIEW

**Comment by dennisschoenmakers** [comment]
> I don't really the way it looks at all. I think it's completely unintuitive that the numbers shown have anything to do with the previous question. 

Here's where I hoped an 'animation' from the previous question could add value: if it would 'stick' at the bottom, it would make intuitively clear to the user that the numbers are about the _previous_ question.

> I tried putting it above the progress bar – which avoids the sense that it's just "floating" at the top of the page, and perhaps avoids the visitor from thinking that the numbers are connected to the current question – but it still doesn't feel right. Which do you prefer?

I agree that the current position is better.

**Comment by antw** [comment]
> Here's where I hoped an 'animation' from the previous question could add value: if it would 'stick' at the bottom, it would make intuitively clear to the user that the numbers are about the previous question.

Agree completely. It would be great if the question could "compress" into the summary (instead of just sliding out of view) but that's well beyond the scope of the animation system ETMobile currently uses. I would be happy to look into this further, but it will be quite tricky<sup>[1]</sup> and I'm committed to the dynamic electricity curves project for a couple of days<sup>[2]</sup>. Therefore, if this is urgently needed I suggest that we merge and revisit it soon.

* [1]: It's not a likely to be a simple animation; we'd have to smoothly tween the shape from the original circle into something which "sticks" near the top of the page, while fading out the rest of the content.
* [2]: Gerard is waiting on me to finish some things before he can work on the charts. Delivery to the client is planned for mid-May.

**Comment by dennisschoenmakers** [comment]
> Agree completely. It would be great if the question could "compress" into the summary (instead of just sliding out of view) but that's well beyond the scope of the animation system ETMobile currently uses.

Well, I think the current working is already pretty good, but the difference between the color scheme of the original and the 'trails' is a bit too large. If we could copy the look and feel more, people will assume the two are related.

**Comment by antw** [comment]
> If we could copy the look and feel more, people will assume the two are related.

Here's how that would look:

screen shot 2017-05-03 at 16 19 54

I think I prefer that.

**Comment by dennisschoenmakers** [comment]
image

**Pull request merged**
