### PR TITLE
Update mobile game

### PR DESCRIPTION
**Pull request by MartLubben**

### CODE REVIEW

**Review by antw — COMMENTED** [review]
I can't comment on the questions themselves, but this looks good and works fine. :+1:

Will English translations for the questions be added?

**Comment by MartLubben** [comment]
> Will English translations for the questions be added?

@antw Yes. My idea was to add them after the feedback round by the client. Although now that I know we do not have a beta version of the mobile game, I think the translations should be added before.

**Comment by antw** [comment]
> Although now that I know we do not have a beta version of the mobile game, I think the translations should be added before.

For what it's worth, Netlify builds a preview version of the site whenever you create or update a pull request. You can show the client this: https://deploy-preview-109--etmobile.netlify.app/

It uses the real database for the production site, but there's no harm in that.

**Comment by MartLubben** [comment]
@antw  Thanks that is quite useful!

**Review by marliekeverweij — APPROVED** [review]

**Comment by marliekeverweij** [comment]
I really like the new questions and enjoyed reading the answers. They're funny! And I've also learned something :) 

I've had some minor textual changes and haven't tested it locally because Anthony and you already did that.

One thing, the 'why' of `heatPumps` question still contains the old LNG-text (row 191-192)

**Pull request merged**
